FROM node:20-alpine

WORKDIR /app

RUN apk update && apk upgrade --no-cache

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
