apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: todosphere
  labels:
    app.kubernetes.io/part-of: todosphere
spec:
  type: ExternalName
  externalName: todosphere-backend.todosphere.svc.cluster.local
