apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todosphere-backend-hpa
  namespace: todosphere
  labels:
    app: todosphere-backend
    app.kubernetes.io/part-of: todosphere
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todosphere-backend
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
