apiVersion: v1
kind: Service
metadata:
  name: todosphere-backend
  namespace: todosphere
  labels:
    app: todosphere-backend
    app.kubernetes.io/part-of: todosphere
spec:
  selector:
    app: todosphere-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
