apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localstack-data
  namespace: todosphere
  labels:
    app: localstack
    app.kubernetes.io/part-of: todosphere
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
